# Generated by Django 4.2.19 on 2025-03-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
