# Generated by Django 4.2.19 on 2025-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_databaseconnection_db_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='db_type',
            field=models.CharField(max_length=10),
        ),
    ]
