# Generated by Django 4.2.19 on 2025-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_databaseconnection_db_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tabela_modelo_pbi', models.CharField(max_length=255)),
                ('nome_tabela_db_origem', models.CharField(max_length=255)),
                ('schema', models.CharField(max_length=255)),
                ('banco', models.CharField(max_length=255)),
                ('conexao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
