# Generated by Django 4.2.19 on 2025-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tabelasemantica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabelasemantica',
            old_name='nome_tabela_db_origem',
            new_name='nome_tabela_origem_db',
        ),
        migrations.AddField(
            model_name='tabelasemantica',
            name='nome_modelo_pbi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
